# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foodexpress' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for foodexpress

  target 'foodexpressTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
